# Generated by Django 4.1.7 on 2023-04-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='direction_instructions',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minimum_age',
        ),
    ]
